name: ✨ Epic
description: Large task or a feature that should be split into multiple sub-tasks.
body:
  - type: textarea
    id: feature_overview
    attributes:
      label: Feature Overview
      description: Provide an overview of the feature to be implemented.

  - type: textarea
    id: user_requirements
    attributes:
      label: User Requirements
      description: List the requirements for the feature as provided by the project manager.

  - type: textarea
    id: design_specifications
    attributes:
      label: Design Specifications
      description: List the specifications for the design of the feature as provided by the designer.

  - type: textarea
    id: technical_implementation
    attributes:
      label: Technical Implementation
      description: Describe how the feature will be implemented from a technical perspective.
      value: |-
        ```[tasklist]
           ### FE Tasks
           - [ ] Add a draft title or issue reference here
        ```
  
        ```[tasklist]
           ### BE Tasks
           - [ ] Add a draft title or issue reference here
        ```
  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.

