name: 🏗️ Feature
description: Create a technical specification for a new feature.
labels:
  - feature
body:
  - type: textarea
    id: feature_overview
    attributes:
      label: Feature Overview
      description: Provide an overview of the feature to be implemented.

  - type: textarea
    id: design_specifications
    attributes:
      label: Design Specifications
      description: List the specifications for the design of the feature as provided by the designer.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.