name: 🛠️ Refactor
description: Request a code refactoring. Something that needs improving while not changing functionality.
labels:
  - refactor
body:
  - type: textarea
    id: current_code
    attributes:
      label: Current Code
      description: Describe the current code and the parts that need to be refactored.

  - type: textarea
    id: refactoring_goal
    attributes:
      label: Refactoring Goal
      description: Describe the goal of the refactoring and how it will improve the code.

  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: List any potential risks or drawbacks of the refactoring.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.
