name: 🐞Bug
description: Report a bug in the application.
labels:
  - bug

body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description & Reproduction Steps
      description: Provide a description of the bug, as well as the steps required to reproduce it.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Log Files
      description: Attach any relevant screenshots and/or log files.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.
