name: 🔥 Support Ticket
description: Issues reported in the support channel.
labels:
  - support

body:
  - type: input
    id: support_ticket
    attributes:
      label: Support Channel Ticket
      description: Link to the support channel ticket.

  - type: textarea
    id: original_message
    attributes:
      label: Original message
      description: Copy/paste the original message from the support channel.

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description & Reproduction Steps
      description: Provide a description of the bug, as well as the steps required to reproduce it.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Log Files
      description: Attach any relevant screenshots and/or log files.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.
