name: ⚙️ DevOps
description: Create DevOps-related tasks and requests. For example, AWS or Heroku related tasks.
labels:
  - devops

body:
  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: Describe the DevOps task to be performed.

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of the task on the project, including any risks or benefits.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.
