name: 📊 Analytics 
description: Create Analytics-related tasks and requests.
labels:
  - analytics

body:
  - type: textarea
    id: references
    attributes:
      label: References & Conversations
      description: Provide links to any relevant references and/or conversations.

  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: Describe the Analytics task to be performed.

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of the task on the project, including any risks or benefits.

  - type: textarea
    id: dependencies
    attributes:
      label: Related Issues & Dependencies
      description: List any related issues & dependencies.
