name: 📦 Miscellaneous 
description: Something that doesn't fit into any category.
labels:
  - miscellaneous

body:
  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: Describe the task to be performed.

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of the task on the project, including any risks or benefits.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to any relevant references, conversations, related issues and dependencies.
